GeneratePDF/objects/Generate_PDF__c/Generate_PDF__c.object-meta.xml
<CustomObject>
    <label>Generate PDF</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Generate PDF</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GeneratePDF/objects/Generate_PDF__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Generate PDF</relationshipLabel>
    <relationshipName>Generate_PDF</relationshipName>
    <type>Lookup</type>
</CustomField>

GeneratePDF/objects/Generate_PDF__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GeneratePDF/objects/GeneratePDF_Config__c/GeneratePDF_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>GeneratePDF Config</label>
</CustomObject>

GeneratePDF/objects/GeneratePDF_Config__c/fields/Enabled_Folders__c.field-meta.xml
<CustomField>
    <fullName>Enabled_Folders__c</fullName>
    <inlineHelpText>Comma-Separated Folder Names</inlineHelpText>
    <label>Enabled Folders</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GeneratePDF/classes/GeneratePDFControllerTest.cls
@isTest
public with sharing class GeneratePDFControllerTest {

    @isTest
    static void generatePdfFileTest() {
        Account account = TestDataFactory.createAccountAsElectricityCustomer();
        insert account;

        EmailTemplate template = [SELECT Id FROM EmailTemplate WHERE Folder.Name != null LIMIT 1];

        Contract contract = new Contract(AccountId = account.Id, Status = 'New');
        insert contract;

        Test.startTest();

        GeneratePDFController.generatePdfFile(template.Id, contract.Id, 'Contract__c', 'TestFileName');
        List<Generate_PDF__c> pdfs = [SELECT Id, Status__c FROM Generate_PDF__c];

        System.assertEquals(1, pdfs.size());
        System.assertEquals('Generated', pdfs[0].Status__c);

        try {
            GeneratePDFController.generatePdfFile(template.Id, 'invalidid', 'Contract__c', 'TestFileName');
        } catch (Exception e) {
            System.assert(e.getMessage().startsWith('Insert failed.'));
        }

        Test.stopTest();
    }

    @isTest
    static void getTableDataTest() {
        Account account = TestDataFactory.createAccountAsElectricityCustomer();
        insert account;

        Contract contract = new Contract(AccountId = account.Id, Status = 'New');
        insert contract;

        Test.startTest();

        Map<String, Object> data = GeneratePDFController.getTableData(contract.Id, 'Contract__c');
        
        System.assert(!((List<String>) data.get('fieldNames')).isEmpty());
        System.assert(((List<Generate_PDF__c>) data.get('records')).isEmpty());

        Test.stopTest();
    }

    @isTest
    static void emailTemplateOptionsTest() {
        insert new GeneratePDF_Config__c(Enabled_Folders__c = 'Fibre_App_Templates');

        Test.startTest();

        // may or may be not empty depend on which environment the test is run
        List<Object> templateOptions = GeneratePDFController.emailTemplateOptions('');
        Test.stopTest();
    }

    @isTest
    static void previewTest() {
        Account account = TestDataFactory.createAccountAsElectricityCustomer();
        insert account;

        EmailTemplate template = [SELECT Id FROM EmailTemplate WHERE Folder.Name != null LIMIT 1];
        
        Contract contract = new Contract(AccountId = account.Id, Status = 'New');
        insert contract;

        Test.startTest();

        PageReference ref = Page.GeneratePDFPreview;

        ref.getParameters().put('tid', template.Id);
        ref.getParameters().put('recid', contract.Id);

        Test.setCurrentPage(ref);

        GeneratePDFController controller = new GeneratePDFController();

        System.assertNotEquals(null, controller.fileTemplateBody);
        Test.stopTest();
    }

    @isTest
    static void validateConfigTest() {
        Account account = TestDataFactory.createAccountAsElectricityCustomer();
        insert account;

        Contract contract = new Contract(AccountId = account.Id, Status = 'New');
        insert contract;

        Test.startTest();

        Boolean isValid = GeneratePDFController.validateConfig(contract.Id, 'AccountId'); 

        Boolean isInvalid = GeneratePDFController.validateConfig(contract.Id, 'InvalidField'); 

        Test.stopTest();
    }
}